export const styles = {
  pageWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    minHeight: '100vh',
    padding: '48px 16px',
    backgroundColor: '#eef0f3',
  },
  componentCard: {
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: '0 4px 24px rgba(0,0,0,0.1), 0 1px 3px rgba(0,0,0,0.06)',
    overflow: 'hidden',
    border: '1px solid #e5e7eb',
    width: 'fit-content',
    // width: '62%',
    // height: '350',  
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#fafbfc',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f2937',
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  badge: {
    fontSize: '12px',
    fontWeight: '500',
    color: '#6b7280',
    backgroundColor: '#f3f4f6',
    padding: '4px 10px',
    borderRadius: '10px',
    border: '1px solid #e5e7eb',
  },
  controlsRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#fff',
  },
  gridPanel: {
    padding: '24px',
    backgroundColor: '#f9fafb',
    position: 'relative' as const,
    borderRadius: '0 0 12px 12px',
    minHeight: '100px',
  },
  seat: {
    position: 'absolute' as const,
    width: '32px',
    height: '32px',
    backgroundColor: '#3b82f6',
    borderRadius: '8px',
    cursor: 'move',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '12px',
    fontWeight: '600',
    border: '2px solid #2563eb',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.2s',
    zIndex: 1
  },
  seatHover: {
    backgroundColor: '#2563eb',
    transform: 'scale(1.05)'
  },
  seatDragging: {
    opacity: 0.5,
    transform: 'scale(1.1)',
    zIndex: 1000
  },
  gridContainer: {
    position: 'relative' as const,
    border: '2px solid #d1d5db',
    backgroundColor: 'white',
    overflow: 'hidden',
    borderRadius: '6px',
  },
  gridContainerDragging: {
    position: 'relative' as const,
    border: '2px dashed #3b82f6',
    backgroundColor: '#eff6ff',
    cursor: 'copy',
    overflow: 'hidden',
    borderRadius: '6px',
  },
  gridCellDroppable: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    border: '1px dashed rgba(34, 197, 94, 0.4)'
  },
  gridCellOccupied: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    border: '1px dashed rgba(239, 68, 68, 0.4)'
  },
  gridCell: {
    position: 'absolute' as const,
    border: '1px solid #e5e7eb',
    backgroundColor: '#f9fafb',
    width: '40px',
    height: '40px'
  },
  trashBin: {
    position: 'absolute' as const,
    bottom: '12px',
    right: '12px',
    width: '48px',
    height: '48px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.35s cubic-bezier(0.34, 1.56, 0.64, 1)',
    boxShadow: '0 2px 8px rgba(0,0,0,0.12)',
    zIndex: 10,
    border: '2px dashed transparent',
    backdropFilter: 'blur(4px)',
  },
  trashBinInactive: {
    backgroundColor: '#e5e7eb',
    color: '#6b7280',
    borderColor: '#d1d5db',
    opacity: 0.6,
  },
  trashBinActive: {
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    color: 'white',
    borderColor: '#ef4444',
    opacity: 1,
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    color: 'black',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '14px',
    fontWeight: '500'
  },
  buttonGreen: {
    backgroundColor: '#10b981'
  },
  buttonBlue: {
    backgroundColor: '#3b82f6'
  },
  buttonPurple: {
    backgroundColor: '#8b5cf6'
  },
  buttonGray: {
    backgroundColor: '#6b7280'
  },
  dropdown: {
    position: 'absolute' as const,
    top: '100%',
    left: 0,
    marginTop: '8px',
    backgroundColor: 'white',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    zIndex: 10,
    minWidth: '192px',
    // padding: '8px'
  },
  dropdownContent: {
    padding: '8px'
  },
  dropdownLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'background-color 0.2s'
  },
  input: {
    width: '64px',
    padding: '4px 8px',
    border: '1px solid #d1d5db',
    borderRadius: '4px',
    fontSize: '14px'
  },
  modal: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '24px',
    borderRadius: '8px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    maxWidth: '400px',
    width: '100%',
    margin: '16px'
  },
  instructionBox: {
    marginTop: '24px',
    backgroundColor: '#eff6ff',
    padding: '16px',
    borderRadius: '8px'
  },
  separator: {
    width: '1px',
    height: '28px',
    backgroundColor: '#e5e7eb',
  },
  // ==================== CARD DECK SLIDER ====================
  cardDeck: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '32px',
    padding: '48px 16px',
    minHeight: '100vh',
    backgroundColor: '#0f172a',
  },
  deckRow: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '28px',
  },
  deckStage: {
    position: 'relative' as const,
    width: '320px',
    height: '420px',
    perspective: '1000px',
    flexShrink: 0,
  },
  deckCard: {
    position: 'absolute' as const,
    inset: 0,
    borderRadius: '20px',
    overflow: 'hidden',
    boxShadow: '0 20px 50px -10px rgba(0,0,0,0.5), 0 8px 20px rgba(0,0,0,0.3)',
    willChange: 'transform, opacity',
    backfaceVisibility: 'hidden' as const,
  },
  deckSideButton: {
    width: '52px',
    height: '52px',
    borderRadius: '50%',
    border: 'none',
    backgroundColor: '#1e293b',
    color: '#e2e8f0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'background-color 0.2s ease, box-shadow 0.2s ease, opacity 0.2s ease',
    boxShadow: '0 6px 18px rgba(0,0,0,0.4)',
  },
  deckSideButtonHover: {
    backgroundColor: '#3b82f6',
    boxShadow: '0 6px 22px rgba(59,130,246,0.5)',
  },
  deckCounter: {
    color: '#94a3b8',
    fontSize: '14px',
    fontWeight: '500',
    minWidth: '60px',
    textAlign: 'center' as const,
  },
  deckHint: {
    color: '#64748b',
    fontSize: '13px',
    textAlign: 'center' as const,
  },
  // ==================== CARD CONTENT (seat layout preview) ====================
  layoutCardInner: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    padding: '24px',
    color: 'white',
  },
  layoutCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '8px',
  },
  layoutCardIcon: {
    width: '44px',
    height: '44px',
    borderRadius: '12px',
    backgroundColor: 'rgba(255,255,255,0.18)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  layoutCardTitle: {
    fontSize: '20px',
    fontWeight: '700',
    margin: 0,
    lineHeight: 1.2,
  },
  layoutCardSubtitle: {
    fontSize: '12px',
    opacity: 0.8,
    marginTop: '2px',
  },
  layoutCardDesc: {
    fontSize: '13px',
    opacity: 0.9,
    lineHeight: 1.5,
    marginTop: '6px',
  },
  layoutPreviewWrap: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '16px',
  },
  layoutPreview: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: '10px',
    padding: '12px',
    display: 'grid',
    gap: '4px',
  },
  layoutPreviewSeat: {
    width: '14px',
    height: '14px',
    borderRadius: '4px',
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  layoutCardFooter: {
    marginTop: '12px',
    fontSize: '12px',
    opacity: 0.7,
    display: 'flex',
    justifyContent: 'space-between',
  },
  deckToolbar: {
    display: 'flex',
    gap: '8px',
    marginBottom: '8px',
  },
  deckToolbarButton: {
    padding: '6px 14px',
    borderRadius: '8px',
    border: '1px solid #334155',
    backgroundColor: '#1e293b',
    color: '#e2e8f0',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    transition: 'all 0.2s',
  },
  deckToolbarButtonActive: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  // ==================== EXPANDED MODE (3-up carousel) ====================
  carousel: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '28px',
    padding: '48px 16px',
    minHeight: '100vh',
    backgroundColor: '#0f172a',
  },
  carouselRow: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '24px',
    width: 'fit-content',
    maxWidth: '100%',
  },
  carouselViewport: {
    position: 'relative' as const,
    overflow: 'hidden',
    flexShrink: 0,
    height: '460px',
  },
  carouselTrack: {
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    gap: '30px',
    padding: '0 30px',
    willChange: 'transform',
    cursor: 'grab',
  },
  carouselTrackDragging: {
    cursor: 'grabbing',
  },
  carouselCardWrap: {
    flexShrink: 0,
    width: '300px',
    height: '440px',
    borderRadius: '20px',
    overflow: 'hidden',
    boxShadow: '0 20px 50px -10px rgba(0,0,0,0.5), 0 8px 20px rgba(0,0,0,0.3)',
    transition: 'transform 0.4s ease, opacity 0.4s ease',
  },
  carouselSideButton: {
    width: '52px',
    height: '52px',
    borderRadius: '50%',
    border: 'none',
    backgroundColor: '#1e293b',
    color: '#e2e8f0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'background-color 0.2s ease, box-shadow 0.2s ease, opacity 0.2s ease',
    boxShadow: '0 6px 18px rgba(0,0,0,0.4)',
  },
  carouselSideButtonDisabled: {
    opacity: 0.3,
    cursor: 'not-allowed',
  },
  carouselSideButtonHover: {
    backgroundColor: '#3b82f6',
    boxShadow: '0 6px 22px rgba(59,130,246,0.5)',
  },
};
